### ISSUE TITLE
d4cRequiem

### ISSUE THREAD

**Issue by roebel** [tuanad121/Python-WORLD#5]
Hello

I wanted to experiment with the D4C measure. I have a question and a suggestion

I don't quite see the difference reason to have a d4cRequiem version. Could you explain what the Requiem means here ? 

On a side note: I stumbled a bit when reading round_matlab :

This is a little bit confusing as the function does in fact not round it just returns a float array that if converted to int does matlab rounding. How about using this as replacement

```
def round_matlab(x):
  return np.floor(x + 0.5*np.sign(x))
 ```
using pure numpy (no numba) this function is 3 times faster than your version and does indeed round.

**Comment by tuanad121** [comment]
> This is a little bit confusing as the function does in fact not round it just returns a float array that if converted to int does matlab rounding. How about using this as replacement
> 
> def round_matlab(x):
>   return np.floor(x + 0.5*np.sign(x))
> using pure numpy (no numba) this function is 3 times faster than your version and does indeed round.
Good catch. Thanks for pointing it out. I will update it soon.

> I don't quite see the difference reason to have a d4cRequiem version. Could you explain what the Requiem means here ?
Unfortunately, I can't be very helpful for the question. Really sorry about that. The 'requiem' things started when Dr. Morise used velvet noise in synthesis. I think he changed the aperiodicity to make it suitable to the velvet noise. 
Dr. Morise is the best person to answer it. You can ask him here:
https://github.com/mmorise/World 
He is very responsive.
Let me know his answer too

^^
