### ISSUE TITLE
Cannot find function "encode_lfbank" and "encode/decode_mcep"

### ISSUE THREAD

**Issue by ericwudayi** [tuanad121/Python-WORLD#7]
Thanks for your word.

As the titled, I can not find this two functions in world/main. How can I reproduce them line by line?

**Comment by tuanad121** [comment]
> Thanks for your word.
> 
> As the titled, I can not find this two functions in world/main. How can I reproduce them line by line?

I forgot to push. I will do so.

**Comment by tuanad121** [comment]
> Thanks for your word.
> 
> As the titled, I can not find this two functions in world/main. How can I reproduce them line by line?

Done. You should see them in main now

**Comment by ericwudayi** [comment]
Thank you very much!

**Comment by tuanad121** [comment]
no problem
